apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fuseworker
  name: fuseworker
spec:
  replicas: 8
  selector:
    matchLabels:
      app: fuseworker
  strategy: {}
  template:
    metadata:
      labels:
        app: fuseworker
    spec:
      containers:
      - image: gcr.io/sdsc-20220719-60951/fuse_zmq
        name: fuseworker
        env:
        - name: FUSE_BROKER
          value: 35.247.84.151
        resources:
          limits:
            cpu: 0.95
            memory: 2.9G
            ephemeral-storage: 1G
          requests:
            cpu: 0.95
            memory: 2.9G
            ephemeral-storage: 1G
        #command: ["sh", "-c", "sleep infinity"]
        command: ["julia", "-e", "import FUSE; FUSE.worker_start()"]
