name: daily_manifest

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

env:
  PTP_READ_TOKEN: ${{ secrets.PTP_READ_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Daily Manifest

    runs-on: ubuntu-latest

    env:
        GKSwstype: 100 # disable Plots.jl interactive output

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Set JULIA_NUM_THREADS=${{ steps.cpu-cores.outputs.count }}
        run: echo "JULIA_NUM_THREADS=${{ steps.cpu-cores.outputs.count }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@latest

      - uses: julia-actions/cache@v1

      - name: Add FuseRegistry
        run: |
          rm -rf ~/.julia/registries/FuseRegistry
          julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/ProjectTorreyPines/FuseRegistry.jl.git")); Pkg.Registry.add("General"); Pkg.Registry.update()'

      - name: Replace git@github.com with https in Package.toml files
        run: |
          find ~/.julia/registries/FuseRegistry -type f -name 'Package.toml' -exec sed -i 's|git@github.com:|https://project-torrey-pines:${{secrets.PTP_READ_TOKEN}}@github.com/|g' {} +

      - run: make install_ci_add

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1

      - run: make manifest_ci_commit

      - name: Debug with tmate if failure + manual triggrer + debug mode
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
